const waterfalls = [
 {
   "X": 608456,
   "Y": 4784015,
   "OBJECTID": 1,
   "SNO": 88,
   "NAME": "Lewis Rd. East Falls",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Stoney Creek",
   "TYPE": "Cascade",
   "RANKING": "C",
   "CLUSTER_AREA": "Stoney Creek-Winona",
   "HEIGHT_IN_M": 8,
   "WIDTH_IN_M": 5,
   "OWNERSHIP": "private",
   "ACCESS_FROM": "McNeilly Rd.",
   "LONGITUDE": -79.66503317,
   "LATITUDE": 43.20112684,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 583986,
   "Y": 4787936,
   "OBJECTID": 2,
   "SNO": 27,
   "NAME": "Little Falls",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Ancaster",
   "TYPE": "Cascade",
   "RANKING": "C",
   "CLUSTER_AREA": "Tiffany-Coldwater",
   "HEIGHT_IN_M": 7,
   "WIDTH_IN_M": 3,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Wilson St. E.",
   "LONGITUDE": -79.96557853,
   "LATITUDE": 43.23954666,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 584594,
   "Y": 4787790,
   "OBJECTID": 3,
   "SNO": 28,
   "NAME": "Tiffany Falls",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Ancaster",
   "TYPE": "Waterfall",
   "RANKING": "A",
   "CLUSTER_AREA": "Tiffany-Coldwater",
   "HEIGHT_IN_M": 21,
   "WIDTH_IN_M": 6,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Wilson St. E. / Tiffany Falls CA",
   "LONGITUDE": -79.95811365,
   "LATITUDE": 43.23816424,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 586478,
   "Y": 4788482,
   "OBJECTID": 4,
   "SNO": 33,
   "NAME": "Scenic Falls",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Hamilton",
   "TYPE": "Cascade",
   "RANKING": "A",
   "CLUSTER_AREA": "Chedoke-Scenic",
   "HEIGHT_IN_M": 20,
   "WIDTH_IN_M": 6,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Scenic Dr. / Chedoke Radial Trail Head",
   "LONGITUDE": -79.93480506,
   "LATITUDE": 43.24418075,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 586872,
   "Y": 4788682,
   "OBJECTID": 5,
   "SNO": 34,
   "NAME": "Lower Princess Falls",
   "ALTERNATE_NAME": "Lower Lang's Falls",
   "COMMUNITY": "Hamilton",
   "TYPE": "Cascade",
   "RANKING": "A",
   "CLUSTER_AREA": "Chedoke-Scenic",
   "HEIGHT_IN_M": 39.5,
   "WIDTH_IN_M": 3,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Hwy 403",
   "LONGITUDE": -79.92992126,
   "LATITUDE": 43.24593608,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 586872,
   "Y": 4788671,
   "OBJECTID": 6,
   "SNO": 35,
   "NAME": "Princess Falls",
   "ALTERNATE_NAME": "Lang's Falls, Upper Princess Falls, Westerly Falls on Chedoke Radial Trail",
   "COMMUNITY": "Hamilton",
   "TYPE": "Waterfall",
   "RANKING": "B",
   "CLUSTER_AREA": "Chedoke-Scenic",
   "HEIGHT_IN_M": 7,
   "WIDTH_IN_M": 2,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Scenic Dr. / Chedoke Radial Trail Land",
   "LONGITUDE": -79.929923,
   "LATITUDE": 43.24583705,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 588109,
   "Y": 4788588,
   "OBJECTID": 7,
   "SNO": 36,
   "NAME": "Upper Sanatorium Falls",
   "ALTERNATE_NAME": "Ravine Mountain Sanatorium, Sanatorium Falls",
   "COMMUNITY": "Hamilton",
   "TYPE": "Cascade",
   "RANKING": "C",
   "CLUSTER_AREA": "Chedoke-Mountview",
   "HEIGHT_IN_M": 9,
   "WIDTH_IN_M": 3,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Sanatorium Rd. / Chedoke Civic Golf Course",
   "LONGITUDE": -79.91470174,
   "LATITUDE": 43.24494626,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 588087,
   "Y": 4788703,
   "OBJECTID": 8,
   "SNO": 37,
   "NAME": "Lower Sanatorium Cascade",
   "ALTERNATE_NAME": "Lower Sanatorium Falls",
   "COMMUNITY": "Hamilton",
   "TYPE": "Cascade",
   "RANKING": "C",
   "CLUSTER_AREA": "Chedoke-Mountview",
   "HEIGHT_IN_M": 4,
   "WIDTH_IN_M": 3,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Beddoe Dr. / Chedoke Civic Golf Course",
   "LONGITUDE": -79.9149543,
   "LATITUDE": 43.24598418,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 587561,
   "Y": 4788642,
   "OBJECTID": 9,
   "SNO": 38,
   "NAME": "Mountview Falls",
   "ALTERNATE_NAME": "Goulding Falls, Water Fall on the Mountain, Easterly Falls on Chedoke Radial Trail",
   "COMMUNITY": "Hamilton",
   "TYPE": "Cascade",
   "RANKING": "B",
   "CLUSTER_AREA": "Chedoke-Mountview",
   "HEIGHT_IN_M": 10,
   "WIDTH_IN_M": 6,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Scenic Dr. / Chedoke Radial Trail Land",
   "LONGITUDE": -79.92144207,
   "LATITUDE": 43.24549626,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 588618,
   "Y": 4788677,
   "OBJECTID": 10,
   "SNO": 39,
   "NAME": "Lower Westcliffe Falls",
   "ALTERNATE_NAME": "West Double Falls",
   "COMMUNITY": "Hamilton",
   "TYPE": "Cascade",
   "RANKING": "B",
   "CLUSTER_AREA": "West Chedoke",
   "HEIGHT_IN_M": 9,
   "WIDTH_IN_M": 6,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Beddoe Dr. / Chedoke Civic Golf Course",
   "LONGITUDE": -79.90841884,
   "LATITUDE": 43.24568788,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 588623,
   "Y": 4788675,
   "OBJECTID": 11,
   "SNO": 40,
   "NAME": "Lower Cliffview Falls",
   "ALTERNATE_NAME": "East Double Falls",
   "COMMUNITY": "Hamilton",
   "TYPE": "Cascade",
   "RANKING": "B",
   "CLUSTER_AREA": "West Chedoke",
   "HEIGHT_IN_M": 4,
   "WIDTH_IN_M": 3,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Beddoe Dr. / Chedoke Civic Golf Course",
   "LONGITUDE": -79.90835759,
   "LATITUDE": 43.24566929,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 588610,
   "Y": 4788645,
   "OBJECTID": 12,
   "SNO": 41,
   "NAME": "Westcliffe Falls",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Hamilton",
   "TYPE": "Cascade",
   "RANKING": "A",
   "CLUSTER_AREA": "West Chedoke",
   "HEIGHT_IN_M": 15,
   "WIDTH_IN_M": 2,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Beddoe Dr. / Chedoke Civic Golf Course",
   "LONGITUDE": -79.90852251,
   "LATITUDE": 43.24540072,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 588666,
   "Y": 4788519,
   "OBJECTID": 13,
   "SNO": 42,
   "NAME": "Cliffview Falls",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Hamilton",
   "TYPE": "Cascade",
   "RANKING": "A",
   "CLUSTER_AREA": "West Chedoke",
   "HEIGHT_IN_M": 15,
   "WIDTH_IN_M": 3,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Beddoe Dr. / Chedoke Civic Golf Course / Scenic Dr. / Cliffview Park",
   "LONGITUDE": -79.90785311,
   "LATITUDE": 43.24425975,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 589270,
   "Y": 4788525,
   "OBJECTID": 14,
   "SNO": 43,
   "NAME": "Lower Chedoke Falls",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Hamilton",
   "TYPE": "Cascade",
   "RANKING": "A",
   "CLUSTER_AREA": "Chedoke",
   "HEIGHT_IN_M": 6,
   "WIDTH_IN_M": 11,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Beddoe Dr. / Chedoke Civic Golf Course",
   "LONGITUDE": -79.90041368,
   "LATITUDE": 43.24424251,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 589254,
   "Y": 4788245,
   "OBJECTID": 15,
   "SNO": 45,
   "NAME": "Chedoke Falls",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Hamilton",
   "TYPE": "Waterfall",
   "RANKING": "A",
   "CLUSTER_AREA": "Chedoke",
   "HEIGHT_IN_M": 18,
   "WIDTH_IN_M": 9,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Beddoe Dr. / Chedoke Civic Golf Course / Scenic Dr",
   "LONGITUDE": -79.90065606,
   "LATITUDE": 43.24172355,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 596704,
   "Y": 4783965,
   "OBJECTID": 16,
   "SNO": 46,
   "NAME": "Upper Glendale Falls",
   "ALTERNATE_NAME": "Glendale Falls",
   "COMMUNITY": "Hamilton",
   "TYPE": "Waterfall",
   "RANKING": "C",
   "CLUSTER_AREA": "Red Hill",
   "HEIGHT_IN_M": 3,
   "WIDTH_IN_M": 3,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Kingsview Dr.",
   "LONGITUDE": -79.80966287,
   "LATITUDE": 43.20227306,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 595894,
   "Y": 4784292,
   "OBJECTID": 17,
   "SNO": 47,
   "NAME": "Buttermilk Falls",
   "ALTERNATE_NAME": "Inglis Falls",
   "COMMUNITY": "Hamilton",
   "TYPE": "Waterfall",
   "RANKING": "A",
   "CLUSTER_AREA": "Red Hill",
   "HEIGHT_IN_M": 23,
   "WIDTH_IN_M": 8,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Mountain Brow Blvd. / Oak-Knoll Park",
   "LONGITUDE": -79.81957437,
   "LATITUDE": 43.20532028,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 595897,
   "Y": 4783744,
   "OBJECTID": 18,
   "SNO": 48,
   "NAME": "Albion Falls",
   "ALTERNATE_NAME": "Mount Albion Falls",
   "COMMUNITY": "Hamilton",
   "TYPE": "Cascade",
   "RANKING": "A",
   "CLUSTER_AREA": "Red Hill",
   "HEIGHT_IN_M": 19,
   "WIDTH_IN_M": 18,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Mountain Brow Blvd. / King's Forest Park",
   "LONGITUDE": -79.81963258,
   "LATITUDE": 43.20038634,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 598382,
   "Y": 4784486,
   "OBJECTID": 19,
   "SNO": 49,
   "NAME": "Little Davis Falls",
   "ALTERNATE_NAME": "Lower Felker's Falls",
   "COMMUNITY": "Hamilton",
   "TYPE": "Waterfall",
   "RANKING": "B",
   "CLUSTER_AREA": "Felker",
   "HEIGHT_IN_M": 3,
   "WIDTH_IN_M": 8,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Quigley Rd.",
   "LONGITUDE": -79.78891992,
   "LATITUDE": 43.20674674,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 598287,
   "Y": 4784126,
   "OBJECTID": 20,
   "SNO": 50,
   "NAME": "Felker's Falls",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Hamilton",
   "TYPE": "Waterfall",
   "RANKING": "A",
   "CLUSTER_AREA": "Felker",
   "HEIGHT_IN_M": 22,
   "WIDTH_IN_M": 6,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Ackland St. / Felker's Falls CA",
   "LONGITUDE": -79.79015317,
   "LATITUDE": 43.20351812,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 600197,
   "Y": 4784566,
   "OBJECTID": 21,
   "SNO": 53,
   "NAME": "Billy Green Falls",
   "ALTERNATE_NAME": "Battlefield Falls",
   "COMMUNITY": "Stoney Creek",
   "TYPE": "Waterfall",
   "RANKING": "B",
   "CLUSTER_AREA": "Glover-Battlefield",
   "HEIGHT_IN_M": 17,
   "WIDTH_IN_M": 6,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Centennial Pky.",
   "LONGITUDE": -79.76656783,
   "LATITUDE": 43.20722828,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 608932,
   "Y": 4783930,
   "OBJECTID": 22,
   "SNO": 89,
   "NAME": "Harvey Falls",
   "ALTERNATE_NAME": "Pond Falls",
   "COMMUNITY": "Stoney Creek",
   "TYPE": "Waterfall",
   "RANKING": "B",
   "CLUSTER_AREA": "Stoney Creek-Winona",
   "HEIGHT_IN_M": 16,
   "WIDTH_IN_M": 3,
   "OWNERSHIP": "private",
   "ACCESS_FROM": "Fifty Rd.",
   "LONGITUDE": -79.65919249,
   "LATITUDE": 43.20029313,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 609506,
   "Y": 4783736,
   "OBJECTID": 23,
   "SNO": 90,
   "NAME": "Promontory Falls",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Stoney Creek",
   "TYPE": "Waterfall",
   "RANKING": "B",
   "CLUSTER_AREA": "Stoney Creek-Winona",
   "HEIGHT_IN_M": 18,
   "WIDTH_IN_M": 1,
   "OWNERSHIP": "private",
   "ACCESS_FROM": "Fifty Rd.",
   "LONGITUDE": -79.65216768,
   "LATITUDE": 43.19846368,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 605967,
   "Y": 4784242,
   "OBJECTID": 24,
   "SNO": 65,
   "NAME": "Jones Rd. Falls",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Stoney Creek",
   "TYPE": "Cascade",
   "RANKING": "C",
   "CLUSTER_AREA": "Stoney Creek-Vinemount",
   "HEIGHT_IN_M": 6,
   "WIDTH_IN_M": 2,
   "OWNERSHIP": "private",
   "ACCESS_FROM": "McNeilly Rd.",
   "LONGITUDE": -79.69561844,
   "LATITUDE": 43.20352374,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 588681,
   "Y": 4796201,
   "OBJECTID": 25,
   "SNO": 66,
   "NAME": "Upper Quarry Cascade",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Flamborough",
   "TYPE": "Cascade",
   "RANKING": "C",
   "CLUSTER_AREA": "Quarry",
   "HEIGHT_IN_M": 4,
   "WIDTH_IN_M": 1.2,
   "OWNERSHIP": "private",
   "ACCESS_FROM": "Mountain Brow Rd.",
   "LONGITUDE": -79.90643033,
   "LATITUDE": 43.3134191,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 586855,
   "Y": 4794313,
   "OBJECTID": 26,
   "SNO": 69,
   "NAME": "Lower Hopkins Cascade",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Flamborough",
   "TYPE": "Cascade",
   "RANKING": "C",
   "CLUSTER_AREA": "Borer's",
   "HEIGHT_IN_M": 6,
   "WIDTH_IN_M": 3.5,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Valley Rd.",
   "LONGITUDE": -79.92924216,
   "LATITUDE": 43.29663443,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 586266,
   "Y": 4793693,
   "OBJECTID": 27,
   "SNO": 70,
   "NAME": "Rock Chapel Falls",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Flamborough",
   "TYPE": "Waterfall",
   "RANKING": "C",
   "CLUSTER_AREA": "Borer's",
   "HEIGHT_IN_M": 8,
   "WIDTH_IN_M": 1.5,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Rock Chapel Rd.",
   "LONGITUDE": -79.93659946,
   "LATITUDE": 43.29112026,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 585266,
   "Y": 4792244,
   "OBJECTID": 28,
   "SNO": 71,
   "NAME": "Dyment Falls",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Flamborough",
   "TYPE": "Waterfall",
   "RANKING": "B",
   "CLUSTER_AREA": "Sydenham",
   "HEIGHT_IN_M": 15.7,
   "WIDTH_IN_M": 4,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Sydenham Rd. lookout",
   "LONGITUDE": -79.949149,
   "LATITUDE": 43.27818867,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 581832,
   "Y": 4792340,
   "OBJECTID": 29,
   "SNO": 74,
   "NAME": "East Greensville Falls",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Flamborough",
   "TYPE": "Cascade",
   "RANKING": "C",
   "CLUSTER_AREA": "Spencer-Logie's",
   "HEIGHT_IN_M": 5.5,
   "WIDTH_IN_M": 1.5,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Crooks Hollow Rd / Crooks Hollow CA",
   "LONGITUDE": -79.9914501,
   "LATITUDE": 43.27943392,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 586171,
   "Y": 4788545,
   "OBJECTID": 30,
   "SNO": 81,
   "NAME": "East Iroquoia Falls",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Hamilton",
   "TYPE": "Waterfall",
   "RANKING": "B",
   "CLUSTER_AREA": "Chedoke-Scenic",
   "HEIGHT_IN_M": 20,
   "WIDTH_IN_M": 1.2,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Hwy 403",
   "LONGITUDE": -79.93857606,
   "LATITUDE": 43.24478309,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 599031,
   "Y": 4784656,
   "OBJECTID": 31,
   "SNO": 82,
   "NAME": "Veevers Falls",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Hamilton",
   "TYPE": "Cascade",
   "RANKING": "C",
   "CLUSTER_AREA": "Felker",
   "HEIGHT_IN_M": 14,
   "WIDTH_IN_M": 2.5,
   "OWNERSHIP": "private",
   "ACCESS_FROM": "Greenhill Ave.",
   "LONGITUDE": -79.78090203,
   "LATITUDE": 43.20819236,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 600038,
   "Y": 4784720,
   "OBJECTID": 32,
   "SNO": 83,
   "NAME": "Centennial Falls",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Stoney Creek",
   "TYPE": "Cascade",
   "RANKING": "B",
   "CLUSTER_AREA": "Glover-Battlefield",
   "HEIGHT_IN_M": 10,
   "WIDTH_IN_M": 4,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Centennial Pky.",
   "LONGITUDE": -79.76849679,
   "LATITUDE": 43.20863578,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 586978,
   "Y": 4794458,
   "OBJECTID": 33,
   "SNO": 111,
   "NAME": "Patterson West Cascade",
   "ALTERNATE_NAME": "Patterson Cascade",
   "COMMUNITY": "Dundas",
   "TYPE": "Cascade",
   "RANKING": "C",
   "CLUSTER_AREA": "Borer's",
   "HEIGHT_IN_M": 4.3,
   "WIDTH_IN_M": 1.2,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Patterson Road",
   "LONGITUDE": -79.92770312,
   "LATITUDE": 43.29792567,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 587028,
   "Y": 4794484,
   "OBJECTID": 34,
   "SNO": 112,
   "NAME": "Patterson East Cascade",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Dundas",
   "TYPE": "Cascade",
   "RANKING": "C",
   "CLUSTER_AREA": "Borer's",
   "HEIGHT_IN_M": 4.6,
   "WIDTH_IN_M": 1.5,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Patterson Road",
   "LONGITUDE": -79.92708269,
   "LATITUDE": 43.29815397,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 590022,
   "Y": 4788461,
   "OBJECTID": 35,
   "SNO": 113,
   "NAME": "Auchmar Falls",
   "ALTERNATE_NAME": "Upper Beckett Falls",
   "COMMUNITY": "Hamilton",
   "TYPE": "Waterfall",
   "RANKING": "C",
   "CLUSTER_AREA": "Chedoke",
   "HEIGHT_IN_M": 12,
   "WIDTH_IN_M": 1.5,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Beckett Drive",
   "LONGITUDE": -79.89116304,
   "LATITUDE": 43.24357691,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 608393,
   "Y": 4783965,
   "OBJECTID": 36,
   "SNO": 87,
   "NAME": "Lewis Rd. West Falls",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Stoney Creek",
   "TYPE": "Waterfall",
   "RANKING": "C",
   "CLUSTER_AREA": "Stoney Creek-Winona",
   "HEIGHT_IN_M": 9,
   "WIDTH_IN_M": 3,
   "OWNERSHIP": "private",
   "ACCESS_FROM": "McNeilly Rd.",
   "LONGITUDE": -79.66581823,
   "LATITUDE": 43.20068576,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 590452,
   "Y": 4788610,
   "OBJECTID": 37,
   "SNO": 99,
   "NAME": "Beckett Falls",
   "ALTERNATE_NAME": "Lower Beckett Falls",
   "COMMUNITY": "Hamilton",
   "TYPE": "Waterfall",
   "RANKING": "C",
   "CLUSTER_AREA": "Chedoke",
   "HEIGHT_IN_M": 3,
   "WIDTH_IN_M": 1.2,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Beckett Drive",
   "LONGITUDE": -79.88584309,
   "LATITUDE": 43.2448669,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 609740,
   "Y": 4783579,
   "OBJECTID": 38,
   "SNO": 91,
   "NAME": "Grand Cascade",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Stoney Creek",
   "TYPE": "Cascade",
   "RANKING": "C",
   "CLUSTER_AREA": "Stoney Creek-Winona",
   "HEIGHT_IN_M": 4,
   "WIDTH_IN_M": 1,
   "OWNERSHIP": "private",
   "ACCESS_FROM": "Fifty Rd.",
   "LONGITUDE": -79.6493195,
   "LATITUDE": 43.19701636,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 609936,
   "Y": 4783449,
   "OBJECTID": 39,
   "SNO": 93,
   "NAME": "West of Fifty Upper Cascade",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Stoney Creek",
   "TYPE": "Cascade",
   "RANKING": "C",
   "CLUSTER_AREA": "Stoney Creek-Winona",
   "HEIGHT_IN_M": 8,
   "WIDTH_IN_M": 1.5,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Fifty Rd.",
   "LONGITUDE": -79.64693365,
   "LATITUDE": 43.19581756,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 610140,
   "Y": 4783397,
   "OBJECTID": 40,
   "SNO": 94,
   "NAME": "Fifty Rd. Cascade",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Stoney Creek",
   "TYPE": "Cascade",
   "RANKING": "C",
   "CLUSTER_AREA": "Stoney Creek-Winona",
   "HEIGHT_IN_M": 10,
   "WIDTH_IN_M": 1.2,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Fifty Rd.",
   "LONGITUDE": -79.64443392,
   "LATITUDE": 43.19531972,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 610386,
   "Y": 4783357,
   "OBJECTID": 41,
   "SNO": 95,
   "NAME": "East of Fifty Falls",
   "ALTERNATE_NAME": "Winona Falls",
   "COMMUNITY": "Stoney Creek",
   "TYPE": "Waterfall",
   "RANKING": "C",
   "CLUSTER_AREA": "Stoney Creek-Winona",
   "HEIGHT_IN_M": 10,
   "WIDTH_IN_M": 1.5,
   "OWNERSHIP": "private",
   "ACCESS_FROM": "Fifty Rd.",
   "LONGITUDE": -79.64141506,
   "LATITUDE": 43.19492372,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 610668,
   "Y": 4783376,
   "OBJECTID": 42,
   "SNO": 96,
   "NAME": "Puddicombe Falls",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Stoney Creek",
   "TYPE": "Cascade",
   "RANKING": "C",
   "CLUSTER_AREA": "Stoney Creek-Winona",
   "HEIGHT_IN_M": 6,
   "WIDTH_IN_M": 2,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Fifty Rd.",
   "LONGITUDE": -79.63794147,
   "LATITUDE": 43.1950535,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 598499,
   "Y": 4784263,
   "OBJECTID": 43,
   "SNO": 103,
   "NAME": "Heritage Green Falls",
   "ALTERNATE_NAME": "Taro Falls",
   "COMMUNITY": "Hamilton",
   "TYPE": "Waterfall",
   "RANKING": "B",
   "CLUSTER_AREA": "Felker",
   "HEIGHT_IN_M": 12.2,
   "WIDTH_IN_M": 1.8,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Ackland Street",
   "LONGITUDE": -79.78751974,
   "LATITUDE": 43.20472388,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 596724,
   "Y": 4783990,
   "OBJECTID": 44,
   "SNO": 109,
   "NAME": "Middle Glendale Falls",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Hamilton",
   "TYPE": "Cascade",
   "RANKING": "C",
   "CLUSTER_AREA": "Red Hill",
   "HEIGHT_IN_M": 3.1,
   "WIDTH_IN_M": 3.4,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Bruce Trail",
   "LONGITUDE": -79.80941236,
   "LATITUDE": 43.20249557,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 598464,
   "Y": 4784239,
   "OBJECTID": 45,
   "SNO": 110,
   "NAME": "Mountain Spring Falls",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Hamilton",
   "TYPE": "Waterfall",
   "RANKING": "B",
   "CLUSTER_AREA": "Felker",
   "HEIGHT_IN_M": 15,
   "WIDTH_IN_M": 2.4,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Ackland Street",
   "LONGITUDE": -79.78795476,
   "LATITUDE": 43.20451238,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 586934,
   "Y": 4794409,
   "OBJECTID": 46,
   "SNO": 107,
   "NAME": "Valley Falls",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Flamborough",
   "TYPE": "Waterfall",
   "RANKING": "C",
   "CLUSTER_AREA": "Borer's",
   "HEIGHT_IN_M": 4.3,
   "WIDTH_IN_M": 4.3,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Bruce Trail at Valley Road",
   "LONGITUDE": -79.92825322,
   "LATITUDE": 43.2974896,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 596164,
   "Y": 4783828,
   "OBJECTID": 47,
   "SNO": 123,
   "NAME": "Pritchard Falls",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Hamilton",
   "TYPE": "Waterfall",
   "RANKING": "C",
   "CLUSTER_AREA": "Red Hill",
   "HEIGHT_IN_M": 4.5,
   "WIDTH_IN_M": 1,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Mountain Brow Blvd. / King's Forest Park",
   "LONGITUDE": -79.81633222,
   "LATITUDE": 43.20110862,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 595034,
   "Y": 4782623,
   "OBJECTID": 48,
   "SNO": 126,
   "NAME": "Billy Monkley Cascade",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Hamilton",
   "TYPE": "Cascade",
   "RANKING": "C",
   "CLUSTER_AREA": "Red Hill",
   "HEIGHT_IN_M": 3,
   "WIDTH_IN_M": 6.4,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Chippewa Rail Trail via Rymal Road/Billy Monkley Bird Sanctuary",
   "LONGITUDE": -79.83044558,
   "LATITUDE": 43.19040318,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 596170,
   "Y": 4785287,
   "OBJECTID": 49,
   "SNO": 122,
   "NAME": "Broman Falls",
   "ALTERNATE_NAME": "Coop's Falls",
   "COMMUNITY": "Hamilton",
   "TYPE": "Waterfall",
   "RANKING": "C",
   "CLUSTER_AREA": "Red Hill",
   "HEIGHT_IN_M": 7,
   "WIDTH_IN_M": 1.1,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Bruce Trail Escarpment Rail Trail at Mohawk Sports Park",
   "LONGITUDE": -79.81600432,
   "LATITUDE": 43.214243,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 595895,
   "Y": 4783719,
   "OBJECTID": 50,
   "SNO": 130,
   "NAME": "Baby Albion Falls",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Hamilton",
   "TYPE": "Waterfall",
   "RANKING": "C",
   "CLUSTER_AREA": "Red Hill",
   "HEIGHT_IN_M": 8.5,
   "WIDTH_IN_M": 1,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Mountain Brow Blvd. / King's Forest Park",
   "LONGITUDE": -79.81966153,
   "LATITUDE": 43.20016152,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 600954,
   "Y": 4785019,
   "OBJECTID": 51,
   "SNO": 54,
   "NAME": "Lower Punchbowl Falls",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Stoney Creek",
   "TYPE": "Waterfall",
   "RANKING": "B",
   "CLUSTER_AREA": "Punchbowl",
   "HEIGHT_IN_M": 6,
   "WIDTH_IN_M": 6,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Mountain Ave.",
   "LONGITUDE": -79.75716844,
   "LATITUDE": 43.21120564,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 601058,
   "Y": 4784925,
   "OBJECTID": 52,
   "SNO": 55,
   "NAME": "Devil's Punchbowl Falls",
   "ALTERNATE_NAME": "Horseshoe Falls, Devil's Punch Bowl",
   "COMMUNITY": "Stoney Creek",
   "TYPE": "Waterfall",
   "RANKING": "A",
   "CLUSTER_AREA": "Punchbowl",
   "HEIGHT_IN_M": 37,
   "WIDTH_IN_M": 3,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Ridge Rd. / Devil's Punchbowl CA",
   "LONGITUDE": -79.75590561,
   "LATITUDE": 43.21034548,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 604108,
   "Y": 4784578,
   "OBJECTID": 53,
   "SNO": 57,
   "NAME": "Dewitt Falls",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Stoney Creek",
   "TYPE": "Cascade",
   "RANKING": "C",
   "CLUSTER_AREA": "Stoney Creek-Fruitland",
   "HEIGHT_IN_M": 7,
   "WIDTH_IN_M": 2,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Dewitt Rd.",
   "LONGITUDE": -79.71843247,
   "LATITUDE": 43.20680717,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 583971,
   "Y": 4787986,
   "OBJECTID": 54,
   "SNO": 78,
   "NAME": "Lower Little Falls",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Ancaster",
   "TYPE": "Cascade",
   "RANKING": "B",
   "CLUSTER_AREA": "Tiffany-Coldwater",
   "HEIGHT_IN_M": 8.2,
   "WIDTH_IN_M": 1.8,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Wilson St. E.",
   "LONGITUDE": -79.96575564,
   "LATITUDE": 43.23999849,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 584208,
   "Y": 4787960,
   "OBJECTID": 55,
   "SNO": 79,
   "NAME": "Ancaster Heights Falls",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Ancaster",
   "TYPE": "Cascade",
   "RANKING": "B",
   "CLUSTER_AREA": "Tiffany-Coldwater",
   "HEIGHT_IN_M": 13.4,
   "WIDTH_IN_M": 1.8,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Wilson St. E.",
   "LONGITUDE": -79.96284102,
   "LATITUDE": 43.23973798,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 586016,
   "Y": 4788500,
   "OBJECTID": 56,
   "SNO": 80,
   "NAME": "West Iroquoia Falls",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Hamilton",
   "TYPE": "Waterfall",
   "RANKING": "B",
   "CLUSTER_AREA": "Chedoke-Scenic",
   "HEIGHT_IN_M": 19.8,
   "WIDTH_IN_M": 1,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Hwy 403",
   "LONGITUDE": -79.94049199,
   "LATITUDE": 43.24439565,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 586199,
   "Y": 4792956,
   "OBJECTID": 57,
   "SNO": 138,
   "NAME": "Sugar Shack Falls",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Dundas",
   "TYPE": "Waterfall",
   "RANKING": "B",
   "CLUSTER_AREA": "Borer's",
   "HEIGHT_IN_M": 9,
   "WIDTH_IN_M": 4,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Rock Chapel Rd. / Rock Chapel Sanctuary",
   "LONGITUDE": -79.93754073,
   "LATITUDE": 43.28449266,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 584226,
   "Y": 4805550,
   "OBJECTID": 58,
   "SNO": 1,
   "NAME": "Progreston Falls",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Flamborough",
   "TYPE": "Waterfall",
   "RANKING": "A",
   "CLUSTER_AREA": "Bronte",
   "HEIGHT_IN_M": 6.7,
   "WIDTH_IN_M": 16.5,
   "OWNERSHIP": "private",
   "ACCESS_FROM": "Progreston Rd.",
   "LONGITUDE": -79.95992137,
   "LATITUDE": 43.39810058,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 590212,
   "Y": 4798123,
   "OBJECTID": 59,
   "SNO": 3,
   "NAME": "Great Falls",
   "ALTERNATE_NAME": "Waterdown Falls, Grindstone Falls, Smokey Hollow Falls, Dunn's Falls, The Falls, Palmer's Falls",
   "COMMUNITY": "Flamborough",
   "TYPE": "Waterfall",
   "RANKING": "A",
   "CLUSTER_AREA": "Grindstone",
   "HEIGHT_IN_M": 10,
   "WIDTH_IN_M": 5,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Mill St / Smokey Hollow Resource Management Area",
   "LONGITUDE": -79.88723848,
   "LATITUDE": 43.33054059,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 590241,
   "Y": 4797890,
   "OBJECTID": 60,
   "SNO": 4,
   "NAME": "Grindstone Cascade",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Flamborough",
   "TYPE": "Cascade",
   "RANKING": "B",
   "CLUSTER_AREA": "Grindstone",
   "HEIGHT_IN_M": 3,
   "WIDTH_IN_M": 5,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Mill St / Smokey Hollow Resource Management Area",
   "LONGITUDE": -79.88691914,
   "LATITUDE": 43.32843944,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 586247,
   "Y": 4793992,
   "OBJECTID": 61,
   "SNO": 6,
   "NAME": "Borer's Falls",
   "ALTERNATE_NAME": "Rock Chapel Falls",
   "COMMUNITY": "Flamborough",
   "TYPE": "Waterfall",
   "RANKING": "A",
   "CLUSTER_AREA": "Borer's",
   "HEIGHT_IN_M": 15,
   "WIDTH_IN_M": 5,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Rock Chapel Rd. / Rock Chapel Sanctuary",
   "LONGITUDE": -79.93678673,
   "LATITUDE": 43.29381436,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 584525,
   "Y": 4791765,
   "OBJECTID": 62,
   "SNO": 10,
   "NAME": "Lower Sydenham Falls",
   "ALTERNATE_NAME": "Sydenham Ravine",
   "COMMUNITY": "Dundas",
   "TYPE": "Waterfall",
   "RANKING": "B",
   "CLUSTER_AREA": "Sydenham",
   "HEIGHT_IN_M": 4,
   "WIDTH_IN_M": 4,
   "OWNERSHIP": "private",
   "ACCESS_FROM": "Livingstone Dr. / Cascades Park",
   "LONGITUDE": -79.95835345,
   "LATITUDE": 43.27395968,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 582900,
   "Y": 4792495,
   "OBJECTID": 63,
   "SNO": 11,
   "NAME": "Tew's Falls",
   "ALTERNATE_NAME": "Hopkins Falls, Tunis Falls",
   "COMMUNITY": "Flamborough",
   "TYPE": "Waterfall",
   "RANKING": "A",
   "CLUSTER_AREA": "Spencer-Logie's",
   "HEIGHT_IN_M": 41,
   "WIDTH_IN_M": 9,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Harvest Rd. / Spencer Gorge / Webster's Falls CA",
   "LONGITUDE": -79.97826607,
   "LATITUDE": 43.28071262,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 582691,
   "Y": 4791988,
   "OBJECTID": 64,
   "SNO": 13,
   "NAME": "Webster's Falls",
   "ALTERNATE_NAME": "Spencer Falls, Hatt's Falls",
   "COMMUNITY": "Flamborough",
   "TYPE": "Waterfall",
   "RANKING": "A",
   "CLUSTER_AREA": "Spencer-Logie's",
   "HEIGHT_IN_M": 22,
   "WIDTH_IN_M": 30,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Fallsview Rd. / Spencer Gorge / Webster's Falls CA",
   "LONGITUDE": -79.98091776,
   "LATITUDE": 43.27617096,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 582612,
   "Y": 4791933,
   "OBJECTID": 65,
   "SNO": 14,
   "NAME": "Baby Webster's Falls",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Flamborough",
   "TYPE": "Waterfall",
   "RANKING": "B",
   "CLUSTER_AREA": "Spencer-Logie's",
   "HEIGHT_IN_M": 9,
   "WIDTH_IN_M": 3,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Fallsview Rd. / Spencer Gorge / Webster's Falls CA",
   "LONGITUDE": -79.98189946,
   "LATITUDE": 43.27568445,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 580590,
   "Y": 4792078,
   "OBJECTID": 66,
   "SNO": 15,
   "NAME": "Darnley Cascade",
   "ALTERNATE_NAME": "Stutt's Falls, Crooks Hollow Falls",
   "COMMUNITY": "Flamborough",
   "TYPE": "Cascade",
   "RANKING": "A",
   "CLUSTER_AREA": "Spencer-Logie's",
   "HEIGHT_IN_M": 4,
   "WIDTH_IN_M": 22,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Crooks Hollow Rd / Darnley Mill ruins",
   "LONGITUDE": -80.0067934,
   "LATITUDE": 43.27720899,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 583406,
   "Y": 4791649,
   "OBJECTID": 67,
   "SNO": 16,
   "NAME": "Dundas Falls",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Dundas",
   "TYPE": "Waterfall",
   "RANKING": "B",
   "CLUSTER_AREA": "Spencer-Logie's",
   "HEIGHT_IN_M": 6.4,
   "WIDTH_IN_M": 6.7,
   "OWNERSHIP": "private",
   "ACCESS_FROM": "King St.",
   "LONGITUDE": -79.97215887,
   "LATITUDE": 43.27304004,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 580185,
   "Y": 4787537,
   "OBJECTID": 68,
   "SNO": 18,
   "NAME": "Mineral Springs Falls",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Ancaster",
   "TYPE": "Cascade",
   "RANKING": "B",
   "CLUSTER_AREA": "DV-Sulphur",
   "HEIGHT_IN_M": 3,
   "WIDTH_IN_M": 2,
   "OWNERSHIP": "private",
   "ACCESS_FROM": "Must view from owner's driveway only",
   "LONGITUDE": -80.01244495,
   "LATITUDE": 43.23636803,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 581355,
   "Y": 4787551,
   "OBJECTID": 69,
   "SNO": 19,
   "NAME": "Hermitage Cascade",
   "ALTERNATE_NAME": "Hermitage Falls",
   "COMMUNITY": "Ancaster",
   "TYPE": "Cascade",
   "RANKING": "B",
   "CLUSTER_AREA": "DV-Sulphur",
   "HEIGHT_IN_M": 4,
   "WIDTH_IN_M": 5,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Sulphur Springs Rd. / Hermitage ruins",
   "LONGITUDE": -79.99803536,
   "LATITUDE": 43.23636879,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 580884,
   "Y": 4787942,
   "OBJECTID": 70,
   "SNO": 20,
   "NAME": "Heritage Falls",
   "ALTERNATE_NAME": "Griffin Falls",
   "COMMUNITY": "Ancaster",
   "TYPE": "Cascade",
   "RANKING": "C",
   "CLUSTER_AREA": "DV-Sulphur",
   "HEIGHT_IN_M": 5,
   "WIDTH_IN_M": 3,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Sulphur Springs Rd. / Hermitage ruins",
   "LONGITUDE": -80.00377795,
   "LATITUDE": 43.23993975,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 583319,
   "Y": 4787240,
   "OBJECTID": 71,
   "SNO": 21,
   "NAME": "Mill Falls",
   "ALTERNATE_NAME": "Wilson Falls, Mill Stream Waterfall, Upper Mill Falls",
   "COMMUNITY": "Ancaster",
   "TYPE": "Waterfall",
   "RANKING": "B",
   "CLUSTER_AREA": "Ancaster-Sulphur",
   "HEIGHT_IN_M": 7,
   "WIDTH_IN_M": 4,
   "OWNERSHIP": "private",
   "ACCESS_FROM": "Old Dundas Rd. / Old Mill Rest.",
   "LONGITUDE": -79.97389756,
   "LATITUDE": 43.23335437,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 583349,
   "Y": 4787311,
   "OBJECTID": 72,
   "SNO": 22,
   "NAME": "Lower Mill Falls",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Ancaster",
   "TYPE": "Cascade",
   "RANKING": "B",
   "CLUSTER_AREA": "Ancaster-Sulphur",
   "HEIGHT_IN_M": 6,
   "WIDTH_IN_M": 4,
   "OWNERSHIP": "private",
   "ACCESS_FROM": "Old Dundas Rd. / Old Mill Rest.",
   "LONGITUDE": -79.97351743,
   "LATITUDE": 43.23399029,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 582762,
   "Y": 4787636,
   "OBJECTID": 73,
   "SNO": 23,
   "NAME": "Canterbury Falls",
   "ALTERNATE_NAME": "Milne Falls",
   "COMMUNITY": "Ancaster",
   "TYPE": "Cascade",
   "RANKING": "B",
   "CLUSTER_AREA": "Ancaster-Sulphur",
   "HEIGHT_IN_M": 9,
   "WIDTH_IN_M": 4,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Old Dundas Rd.",
   "LONGITUDE": -79.98069671,
   "LATITUDE": 43.23698099,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 582817,
   "Y": 4787627,
   "OBJECTID": 74,
   "SNO": 24,
   "NAME": "Little Canterbury Falls",
   "ALTERNATE_NAME": "N/A",
   "COMMUNITY": "Ancaster",
   "TYPE": "Cascade",
   "RANKING": "C",
   "CLUSTER_AREA": "Ancaster-Sulphur",
   "HEIGHT_IN_M": 5,
   "WIDTH_IN_M": 2,
   "OWNERSHIP": "public",
   "ACCESS_FROM": "Old Dundas Rd.",
   "LONGITUDE": -79.98002079,
   "LATITUDE": 43.23689392,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 },
 {
   "X": 583391,
   "Y": 4787770,
   "OBJECTID": 75,
   "SNO": 26,
   "NAME": "Sherman Falls",
   "ALTERNATE_NAME": "Smith's Falls, Whitton Falls, Fairy Falls, Angel Falls",
   "COMMUNITY": "Ancaster",
   "TYPE": "Waterfall",
   "RANKING": "A",
   "CLUSTER_AREA": "Ancaster-Sulphur",
   "HEIGHT_IN_M": 17,
   "WIDTH_IN_M": 8,
   "OWNERSHIP": "private",
   "ACCESS_FROM": "Lions Club Rd.",
   "LONGITUDE": -79.97293085,
   "LATITUDE": 43.23811814,
   "TYPE": "City Waterfalls",
   "LIKES": 0,
   "DISLIKES": 0,
   "COMMENT": ""
 }
]